-- Upload complete menu for Ashim's Canteen
-- Delete existing menu items (optional - comment out if you want to keep existing items)
DELETE FROM menu_items;

-- Insert all menu items with emojis
INSERT INTO menu_items (name, price) VALUES
-- ROLLS 🌯
('🌯 Veg Roll', 25),
('🧀 Paneer Roll', 50),
('🥚 Egg Roll', 40),
('🥚🥚 Double Egg Roll', 55),
('🍗 Chicken Roll', 60),
('🍗🥚 Chicken Egg Roll', 65),

-- STARTERS 🍴
('🍗 Chicken Lollipop', 90),
('🍗 Chicken Lamba', 100),
('🍗 Chicken Pakoda', 100),
('🥗 Veg Pakoda', 80),
('🧅 Onion Pakoda', 70),
('🧀 Paneer Pakoda', 90),
('🍟 Finger Chips', 60),

-- SOUTH INDIAN 🍽️
('🥞 Masala Dosa', 45, 'South Indian'),
('🥞 Onion Dosa', 35, 'South Indian'),
('🥞 Onion Masala Dosa', 40, 'South Indian'),
('🥞 Butter Dosa', 60, 'South Indian'),
('🥞 Egg Masala Dosa', 70, 'South Indian'),
('🥞 Butter Masala Dosa', 55, 'South Indian'),
('🥞 Plain Dosa', 30, 'South Indian'),
('🥞 Cheese Masala Dosa', 60, 'South Indian'),
('🥞 Egg Dosa', 60, 'South Indian'),
('🥞 Uttapam (SPL)', 65, 'South Indian'),

-- SANDWICH 🥪
('🥪 Chotai Sandwich', 45, 'Sandwich'),
('🥪 Vassi Sandwich', 45, 'Sandwich'),
('🥪 Badani Sandwich', 40, 'Sandwich'),
('🥪 Cheese Golla Sandwich', 40, 'Sandwich'),
('🥪 Veg Sandwich', 40, 'Sandwich'),
('🥪 Veg Cheese Sandwich', 50, 'Sandwich'),
('🥪 Paneer Sandwich', 60, 'Sandwich'),
('🥪 Paneer Cheese Sandwich', 75, 'Sandwich'),
('🥪 Dahi Sandwich', 40, 'Sandwich'),
('🥪 Egg Sandwich', 50, 'Sandwich'),
('🥪 Chicken Sandwich', 60, 'Sandwich'),
('🥪 Chicken Cheese Sandwich', 75, 'Sandwich'),

-- CHINESE 🥡
('🍜 Veg Noodles', 35, 'Chinese'),
('🍜 Egg Noodles', 45, 'Chinese'),
('🍜 Chicken Noodles', 60, 'Chinese'),
('🍜 Veg S Noodles', 45, 'Chinese'),
('🍜 Egg S Noodles', 50, 'Chinese'),
('🍜 Chicken S Noodles', 70, 'Chinese'),
('🥟 Momo (Veg)', 40, 'Chinese'),
('🥟 Momo (Non-Veg)', 50, 'Chinese'),
('🥟 Fried Momo (Veg)', 50, 'Chinese'),
('🥟 Fried Momo (Non-Veg)', 60, 'Chinese'),

-- MAGGI 🍝
('🍝 Butter Maggi', 30, 'Maggi'),
('🍝 Masala Maggi', 40, 'Maggi'),
('🍝 Ashwini Maggi', 45, 'Maggi'),
('🍝 Bhatu Maggi', 40, 'Maggi'),
('🍝 Tibri Maggi', 45, 'Maggi'),
('🍝 Egg Maggi', 50, 'Maggi'),
('🍝 Chicken Maggi', 60, 'Maggi'),
('🍝 Fried Maggi', 35, 'Maggi'),
('🍝 Egg Fried Maggi', 45, 'Maggi'),
('🍝 Plain Maggi', 25, 'Maggi'),
('🍝 Chicken Fried Maggi', 60, 'Maggi'),
('🍝 Schez Fried Maggi', 50, 'Maggi'),
('🍝 Schez Egg Fried Maggi', 55, 'Maggi'),
('🍝 Schez Chicken Fried Maggi', 70, 'Maggi'),

-- DRINKS ☕
('☕ Tea', 10, 'Drinks'),
('☕ Coffee', 20, 'Drinks'),
('🥛 Hot Milk', 20, 'Drinks'),
('🥛 Haldi Milk', 20, 'Drinks'),
('🥤 Bornvita', 30, 'Drinks'),
('🥤 Horlicks', 30, 'Drinks'),
('🍫 Chocolate Shake', 50, 'Drinks'),
('🥤 Badam Shake', 50, 'Drinks'),
('🌹 Rose Shake', 50, 'Drinks'),
('🥭 Mango Shake', 50, 'Drinks'),
('🍪 Oreo Shake', 50, 'Drinks'),
('🍌 Banana Shake', 40, 'Drinks'),
('🍋 Nimbu Pani', 15, 'Drinks'),
('🥤 Jaljira', 20, 'Drinks'),
('🥤 Masala Cold Drink', 40, 'Drinks'),
('☕ Cold Coffee', 35, 'Drinks'),
('🥤 Cold Bornvita', 35, 'Drinks'),
('🥤 Cold Horlicks', 35, 'Drinks'),

-- DAL 🍲
('🍲 Dal Fry', 50, 'Dal'),
('🍲 Dal Tadka', 60, 'Dal'),
('🍲 Egg Tadka', 70, 'Dal'),
('🍲 Chicken Tadka', 80, 'Dal'),
('🍲 Dal Makhani', 70, 'Dal'),

-- SNACKS 🍳
('🥚 Boiled Egg', 25, 'Snacks'),
('🥚 Fried Boiled Egg', 30, 'Snacks'),
('🥚 Poch', 15, 'Snacks'),
('🥚 Omlette', 20, 'Snacks'),
('🥚 Cheese Omlet', 35, 'Snacks'),
('🥚 Egg Bhujia', 30, 'Snacks'),
('🍗 Chicken Egg Bhujia', 40, 'Snacks'),
('🥚 Bread Omlette', 35, 'Snacks'),
('🥚 Cheese Bread Omlette', 50, 'Snacks'),
('🍞 Bread Butter', 20, 'Snacks'),
('🍞 Bread Veg Bhujia', 30, 'Snacks'),
('🍞 Bread Egg Bhujia', 35, 'Snacks'),
('🍞 French Toast', 30, 'Snacks'),
('🍞 S.C.F.T', 30, 'Snacks'),
('🍞 Tinku', 30, 'Snacks'),
('🍞 Delta', 50, 'Snacks'),
('🍔 Veg Burger', 35, 'Snacks'),
('🍔 Veg Cheese Burger', 50, 'Snacks'),
('🍔 Egg Burger', 35, 'Snacks'),
('🍔 Egg Cheese Burger', 50, 'Snacks'),
('🍔 Chicken Burger', 60, 'Snacks'),
('🍔 Chicken Cheese Burger', 75, 'Snacks'),
('🍛 Pao Bhaji', 40, 'Snacks'),
('🍛 Vada Pao', 30, 'Snacks'),
('🍪 Parle Masala', 20, 'Snacks'),
('🍚 Poha', 35, 'Snacks'),
('🍛 Pappu Bhujia', 22, 'Snacks'),
('🥚 Egg Chat', 40, 'Snacks'),
('🥔 Allu Chat', 50, 'Snacks'),
('🍛 Chole Bhature', 48, 'Snacks'),

-- BREADS 🫓
('🫓 Lachha Paratha', 18, 'Breads'),
('🫓 Allu Paratha', 25, 'Breads'),
('🫓 Onion Paratha', 25, 'Breads'),
('🫓 Cheese Paratha', 40, 'Breads'),
('🫓 Paneer Paratha', 50, 'Breads'),
('🫓 Allu Onion Paratha', 30, 'Breads'),
('🫓 Allu Cheese Paratha', 40, 'Breads'),
('🫓 Paneer Cheese Paratha', 55, 'Breads'),
('🫓 Plain Paratha', 10, 'Breads'),
('🫓 Tawa Roti', 7, 'Breads'),
('🫓 Tawa Butter Roti', 10, 'Breads'),

-- TANDOOR 🔥
('🫓 Tandoori Butter Roti', 15, 'Tandoor'),
('🫓 Tandoori Roti', 12, 'Tandoor'),
('🫓 Allu Roti', 20, 'Tandoor'),
('🫓 Onion Roti', 30, 'Tandoor'),
('🫓 Allu Cheese Roti', 50, 'Tandoor'),
('🫓 Kulcha', 40, 'Tandoor'),
('🫓 Masala Kulcha', 50, 'Tandoor'),
('🍗 Tandoori Chicken', 110, 'Tandoor'),
('🍗 Chicken Tikka', 100, 'Tandoor'),
('🧀 Paneer Tikka', 100, 'Tandoor'),
('🍗 Reshmi Kabab', 120, 'Tandoor'),

-- RICE 🍚
('🍚 Veg Fried Rice', 60, 'Rice'),
('🍚 Egg Fried Rice', 70, 'Rice'),
('🍚 Chicken Fried Rice', 80, 'Rice'),
('🍚 Mix Fried Rice', 90, 'Rice'),
('🍚 Paneer Fried Rice', 90, 'Rice'),
('🍚 Jira Rice', 35, 'Rice'),
('🍚 Curd Rice', 35, 'Rice'),
('🍚 Lemon Rice', 35, 'Rice'),
('🍚 Delta Rice', 35, 'Rice'),
('🍚 Egg Delta Rice', 40, 'Rice'),
('🍚 Chicken Delta Rice', 50, 'Rice'),
('🍚 Veg Schezwan Rice', 70, 'Rice'),
('🍚 Egg Schezwan Rice', 80, 'Rice'),
('🍚 Chicken Schezwan Rice', 100, 'Rice'),
('🍚 Biriyani', 150, 'Rice'),

-- VEG CURRIES 🥘
('🥘 Veg Panjabi', 70, 'Veg Curries'),
('🥘 Veg Ghuna', 80, 'Veg Curries'),
('🥘 Mix Veg', 70, 'Veg Curries'),
('🥘 Nabratan Korma', 120, 'Veg Curries'),
('🥘 Veg Korma', 90, 'Veg Curries'),
('🥔 Kashmiri Alu Dum', 90, 'Veg Curries'),
('🥔 Allu Jira', 70, 'Veg Curries'),
('🥔 Allu Chilly', 70, 'Veg Curries'),
('🌽 Babycorn Masala', 80, 'Veg Curries'),
('🌽 BCBM', 85, 'Veg Curries'),
('🌽 Babycorn Chilly', 90, 'Veg Curries'),
('🍄 Mushroom Masala', 110, 'Veg Curries'),
('🍄 Mushroom B Masala', 100, 'Veg Curries'),
('🥘 Chana Masala', 70, 'Veg Curries'),
('🥘 Veg Jhal Fry', 70, 'Veg Curries'),

-- PANEER 🧀
('🧀 P.B. Masala', 80, 'Paneer'),
('🧀 Paneer Do Pyaza', 80, 'Paneer'),
('🧀 Paneer Panjabi', 90, 'Paneer'),
('🧀 Paneer Varta', 90, 'Paneer'),
('🧀 Paneer Kadai', 90, 'Paneer'),
('🧀 Paneer Bhujia', 80, 'Paneer'),
('🧀 Paneer Makhani', 80, 'Paneer'),
('🧀 Paneer Handi', 90, 'Paneer'),
('🧀 Paneer Chilli', 90, 'Paneer'),

-- CHICKEN CURRIES 🍗
('🍗 Chicken Do Pyaza', 90, 'Chicken'),
('🍗 Chicken Kadai', 90, 'Chicken'),
('🍗 Chicken Panjabi', 90, 'Chicken'),
('🍗 Chicken Korma', 90, 'Chicken'),
('🍗 Chicken Kossa', 90, 'Chicken'),
('🍗 C B Masala', 90, 'Chicken'),
('🍗 Chicken Masala', 90, 'Chicken'),
('🍗 Chicken Curry', 90, 'Chicken'),
('🍗 Chicken Ghuna', 90, 'Chicken'),
('🍗 Chicken Handi', 90, 'Chicken'),
('🍗 Chicken Nurjahani', 100, 'Chicken'),
('🍗 Chicken Kashmiri', 100, 'Chicken'),
('🍗 Leg Masala', 90, 'Chicken'),
('🍗 Chicken Tikka Masala', 100, 'Chicken'),
('🍗 Kima Masala', 90, 'Chicken'),
('🍗 Kima Curry', 90, 'Chicken'),
('🍗 Chilly Chicken', 90);
